### PR TITLE
Included the reporting points of austria at private airfields

### PR DESCRIPTION
**Pull request by Surkes**
As title says. Syntax "nameofpoint ICAO"
Source: openflightmaps.org Austria/isolated
https://www.openflightmaps.org/

### CODE REVIEW

**Comment by Turbo87** [comment]
what's the license of that dataset? are we allowed to redistribute it?

**Comment by Surkes** [comment]
Due to your contribution I looked at the license of openflightmaps. 
Someone can use the database of OFM but we have to set a notice.

So if I understand that correct it would be possible to set a header comment over the Openflightmaps waypoints in our cup-file.

**Comment by Turbo87** [comment]
I'm not sure if that's possible. http://download.naviter.com/docs/CUP-file-format-description.pdf does not mention anything about comments 🤔

**Comment by Surkes** [comment]
Look at the cup from AustroControl. They set a header with all necessary informations before the waypoints.
https://www.austrocontrol.at/jart/prj3/ac/data/dokumente/austria_acg_waypoints_2019-03-28_2019-02-22_1302179.cup

**Comment by Turbo87** [comment]
ah okay, if that works with SeeYou and XCSoar then that would be fine, yeah 👍

**Comment by hor63** [comment]
Please note that we (at least I am) using .cup files at other places too. For example:

- [prosoar.de](http://prosoar.de/) for route planning (without SeeYou).
- [Java Top Task](https://www.flugwetter.de/getjnlpfile.php?src=jtt.jnlp) from DWD to have the same turn points as on XCSoar and in ProSoar

Do the comment sections work in there too?
Would instead a file LICENSES with links to the respective .CUP (and other) files, their owner and applicable license in the git repository and [XCSoar download](http://download.xcsoar.org/) suffice?

**Pull request merged**
