### PR TITLE
Update USA_PG_REG5-8.cup

### PR DESCRIPTION
**Pull request by ventus99**
What is the purpose of this change? What does it change?
--------------------------------------------------------

What is the source of the data (for e.g. new frequencies)?
----------------------------------------------------------

### CODE REVIEW

**Comment by ventus99** [comment]
Sorry, opened this new one by mistake when editing.

**Comment by ventus99** [comment]
It's not clear to me if this is failing or the previous version of USA_PG_REG1-4.cup is failing and I can't properly test this until that one is fixed.  Is there a way to re run the Travis CI once the fix for 1-4 is accepted?

**Comment by lordfolken** [comment]
rebase your code on the current master branch, and it should work.

**Comment by ventus99** [comment]
@lordfolken Looks like I finally got it!

**Review by lordfolken — APPROVED** [review]

**Pull request merged**
