### PR TITLE
feat: Autogenerate both waypoints-special manifests.

### PR DESCRIPTION
**Pull request by csindle**
Autogen:

1. `waypoints-special.json`
1. `waypoints-special.repository`

Also fixes the [assumed] latent bug that the `waypoints` and the `waypoints-special` directories had different `types` in the repository file, namely: `waypoint` and `waypoints`.

### CODE REVIEW

**Comment by lordfolken** [comment]
Can you rebase and force push please? 
Also could you fix the codacy alerts?

**Comment by csindle** [comment]
> Also could you fix the codacy alerts?

Yip, I'll try.  Though w.r.t. to Docstrings Codacity seem to be incorrect (according to PEP257) quite often (though so am I).

E.g. :
The "mistake" here https://app.codacy.com/gh/XCSoar/xcsoar-data-content/pullRequest?prid=8376685 
is literally in the correct [PEP257](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings) example.

I understand that we have to stick to some standards...

**Comment by csindle** [comment]
> Can you rebase and force push please?

Ok, done.

**Comment by lordfolken** [comment]
Yes i know. i often don't agree with codacy either. ;) But as you say.. some standards.

**Review by lordfolken — APPROVED** [review]

**Pull request merged**
