### PR TITLE
Remove low E Airways - Canada Airspace

### PR DESCRIPTION
**Pull request by ventus99**
Remove low E Airways.  Uploaded wrong file previously.
# Pull Request

### CODE REVIEW

**Comment by ventus99** [comment]
> @ventus99 Can you please elaborate on why these changes are made? There's a lot of removals in the diff so I'm curious what the reason for these changes are. What are "low E Airways"? Or are we talking about E airspaces?

In Canada airways are class B above 12,500ft and class E below 12,500ft.  The class E is not really useful information to glider pilots and makes a lot of clutter in XCSoar.  I create a version with the class E just in case someone wants it.  I accidentally uploaded that version this time.

**Comment by rawtaz** [comment]
Sorry if this is a silly question, but I don't understand why E airspace below 12500 ft is less relevant than the B airspace above 12500 ft - if we remove the E airspace, why do we want to keep the B airspace? Glider more often fly below 12500 than above 12500 ft, I figure.

**Comment by ventus99** [comment]
> Sorry if this is a silly question, but I don't understand why E airspace below 12500 ft is less relevant than the B airspace above 12500 ft - if we remove the E airspace, why do we want to keep the B airspace? Glider more often fly below 12500 than above 12500 ft, I figure (without knowing what fancy thermals you have over there :D).

Not a silly question.  I think this is unique to Canada but I am not certain.  We have essentially three types of airways.  High level class A +18,000ft, low level class B 12,500ft-18,000ft and low level class E 2200ftAGL-12,500ft.  There are some exceptions.  The low level class E airways don't mean much to glider pilots as it does not require a clearance.  It does require higher vfr visibility and ceiling limits but glider pilots are very unlikely to be flying xcountry in conditions below 3sm visibility and 1000ft AGL ceilings.  In the places where most gliders pilots fly it is about half or more of the airspace we fly in.  It adds a huge amount of clutter to the screen.  You could select to not display class E in XCSoar but then you would not see class E control zones or other pertinent class E zones.  If you wanted warnings for class E zones it would be essentially unusable because of the amount of warnings you would get.  Since the airways don't really affect us, it is best to not include it.  I give people the option to display everything if they want by downloading the file from my website.  But I don't think anyone uses it.

I have always uploaded my 'nolowE' version which really is 'no low E airways'.  I don't think the 'all' version is very useful to anyone and it was a mistake that I uploaded it this time.

**Comment by ventus99** [comment]
> Sorry if this is a silly question, but I don't understand why E airspace below 12500 ft is less relevant than the B airspace above 12500 ft - if we remove the E airspace, why do we want to keep the B airspace? Glider more often fly below 12500 than above 12500 ft, I figure (without knowing what fancy thermals you have over there :D).

Sorry, I didn't answer why we want to keep class B.

In my area of flying we do get thermals above 12,500ft on a somewhat regular basis.  Since class B requires a clearance, I think it is very important to display or have warnings setup.  I usually set class B to Warn but not Display.  In some places I display the class B if I am planning to go above 12,500ft.  In the Rocky Mountains this is commonly necessary.

**Comment by rawtaz** [comment]
Thanks so much for elaborating @ventus99, very interesting and it all makes sense :)

**Review by rawtaz — APPROVED** [review]

**Pull request merged**
