### PR TITLE
Update Canada_Airspace.txt

### PR DESCRIPTION
**Pull request by ventus99**
August 12 Update

What is the purpose of this change? What does it change?
--------------------------------------------------------

What is the source of the data (for e.g. new frequencies)?
----------------------------------------------------------

### CODE REVIEW

**Comment by ventus99** [comment]
@lordfolken this check isn't completing.  Can you help me get it finished?

**Comment by rawtaz** [comment]
@ventus99 I noticed that "special" characters aren't encoded properly anymore, see e.g. the change in https://github.com/XCSoar/xcsoar-data-content/pull/147/files#diff-28ed5673ad72ce080d954633484427dbe61955e3a18cad65ba4ad5b514f5ba0fL19043 for an example. Did you perhaps save the file with a diffrent encoding this time, or copy some text in a different way?

**Comment by lordfolken** [comment]
This needs a rewrite to github actions. travis is deprecated, which is why the check doesn't complete.

**Comment by ventus99** [comment]
> This needs a rewrite to github actions. travis is deprecated, which is why the check doesn't complete.

Is this a change I need to make or is it a task for the admins?

**Pull request merged**
