### PR TITLE
Update CA-ASP-National-XCSoar.txt

### PR DESCRIPTION
**Pull request by ventus99**
August 10 update

# Pull Request

### CODE REVIEW

**Review by lordfolken — APPROVED** [review]
Fine for me. 
Do you want to merge now, or on the 10th of august?
Could you download the resulting file and use that for your next changes? That way all the whitespace changes from precommit would be incoorporsted and the diffs more readable.

**Comment by lordfolken** [comment]
@prscheduler 2023-08-09 00:00

**Comment by lordfolken** [comment]
@prscheduler 2023-08-09 23:55 PDT

**Comment by ventus99** [comment]
> Merge re-scheduled for 2023-08-09 23:55 PDT time. If you want to change the scheduled time, just comment again with a new time.

That's perfect

**Comment by ventus99** [comment]
>Could you download the resulting file and use that for your next changes? That way all the whitespace changes from precommit would be incoorporsted and the diffs more readable.

I don't manually edit the file.  It is newly generated each cycle.  So I can't really use the file again.  I can look into getting rid of the whitespace going forward though.

**Pull request merged**
