### PR TITLE
French air space

### PR DESCRIPTION
**Pull request by mlep**
French air space, from the FFVP (French Gliding Association).  https://www.ffvp.fr/liens-utiles-telechargements

### CODE REVIEW

**Comment by Turbo87** [comment]
do we have permission to redistribute the data? why do we need to maintain the data ourselves instead of linking to the official source?

**Comment by mlep** [comment]
> do we have permission to redistribute the data? 

Before uploading the file, I looked at some other countries airspaces and did not notice a licence mentionned. Here, the file header states "This file is provided free of charge with no warrantees,  expressed or implied." Is it enough?

> why do we need to maintain the data ourselves instead of linking to the official source?

Actually, if the file manager of XCSoar could go fetch the file from its original source, that will be very convenient!

**Comment by lordfolken** [comment]
> Actually, if the file manager of XCSoar could go fetch the file from its original source, that will be very convenient!

It can! have a look at https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json

**Comment by mlep** [comment]
> It can! have a look at https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json

Oh, great! So my PR is not relevant. Sorry for taking your time (I am still learning about XCsoar data management).
Closing...

**Pull request closed without merging**
