### PR TITLE
Rename USA_PG_REG9-12 to USA_PG_REG9-12.cup

### PR DESCRIPTION
**Pull request by ventus99**
What is the purpose of this change? What does it change?
--------------------------------------------------------

What is the source of the data (for e.g. new frequencies)?
----------------------------------------------------------

### CODE REVIEW

**Comment by rawtaz** [comment]
@ventus99 Why did you close #134 and open this one? I don't get it.

**Comment by ventus99** [comment]
> @ventus99 Why did you close #134 and open this one? I don't get it.

I can't figure out why these are failing.  So I am trying different things.  Some seem to pass at random.

**Comment by rawtaz** [comment]
@ventus99 But if you have a PR already, you can just push to the branch of the PR to update the PR. There's no need to close the PR and create a new one. It's just creating confusion and a mess :) Am I missing something?

**Comment by ventus99** [comment]
> @ventus99 But if you have a PR already, you can just push to the branch of the PR to update the PR (at which point the tests will be re-run based on the new commits you pushed). There's no need to close the PR and create a new one. It's just creating confusion and a mess :) Am I missing something?

Well you can see that I can't even get a .cup file to pass a simple test.  I don't know what I am doing.

**Comment by rawtaz** [comment]
I debugged this a bit and it seems that the problem is the lines that start with `ObsZone=`and end with the key `AAT=1`.

The error in the [failing test](https://travis-ci.org/github/XCSoar/xcsoar-data-content/builds/764604610) is "A taskpoint *does not* contain key AAT", which is unfortunately badly worded. The intention is more accurately "A taskpoint *may not* contain key AAT".

As can be seen in [the parser's code at line 315](https://github.com/Turbo87/aerofiles/blob/2829338315635e66bc52ad35b900e282fd07075b/aerofiles/seeyou/reader.py#L315) this error happens when the line is like `ObsZone=1,Style=1,R1=1609m,A1=180,AAT=1` instead of `ObsZone=1,Style=1,R1=1609m,A1=180`.

I'm not too knowledgable about the CUP file format other than what I can read in the [CUP file format reference](http://download.naviter.com/docs/CUP-file-format-description.pdf) so I'm wondering if you have any idea how those `AAT=1` key-values came to be? Did you use SeeYou or something and this added it, or have you done some manual editing where they were added?

I presume (haven't tried it though) that the `,AAT=1` part must be removed, but it would be good to find the *cause* of this issue instead of just working around it temporarily.

**Comment by rawtaz** [comment]
@ventus99 I edited the commit so that it renames the file to .cup. Feel free to ask for help if you're ever stuck with managing files, commits and PRs, it's better that we help you out and keep it all clean than that we have a bunch of confusing PRs :+1:

The `AAT=1` problem persists though - can you tell me what changed between your earlier pull requests with .cup files and this one? Have you e.g. updated SeeYou or whichever software you use to generate the files?

**Comment by rawtaz** [comment]
@ventus99 Can you please look into what I asked? If you haven't changed any software I'd be surprised if all of a sudden it starts spitting out files that are differently formatted from before, so I'm thinking something changed (e.g. new version of the software which contains some new formats in the file or whatever). Would just be good to know of any such thing before digging deeper.

**Comment by ventus99** [comment]
@rawtaz I did upgrade my version of SeeYou which gives the AAT=1 flags which I did not have before.  But I did try my old version of SeeYou on a separate computer and that didn't work either.

**Comment by ventus99** [comment]
I am going to try from the start again and see if I can make a file that works

**Comment by lordfolken** [comment]
The git history is a bit of a mess... mind to clean it up a bit and do a git push? I merged your other request.

**Comment by ventus99** [comment]
> The git history is a bit of a mess... mind to clean it up a bit and do a git push? I merged your other request.

I am not sure how to do that.  Should I close the pull request and make another?

**Comment by ventus99** [comment]
> I'm about to clean this one up, but I need to ask; The file `USA_PG_REG5-8.cup` shouldn't be deleted, should it? This PR currently deletes that file, and even if that file for some reason should be deleted, that should be done in a separate PR. But I'd like your verification before I exclude the deletion of that file from this PR :)
> 
> Also, can you verify that the `USA_PG_REG9-12.cup` file is now completely up do snuff and ready to be merged?

No, USA_PG_REG5-8 should not be deleted.  The rebasing edited this file which I did not want.  Didn't know how to fix that.  

Yes, USA_PG_REG9-12.cup should be good to be merged.  

Thank you for your help getting these files uploaded @lordfolken @rawtaz

**Review by rawtaz — APPROVED** [review]
Awesome, finally!

**Comment by ventus99** [comment]
> Awesome, finally!

Yes, thank you.  Can I bother you to merge the links at xcsoar-data-repository as well?

**Pull request merged**
