### PR TITLE
Add of French Alps saiplane outlanding fields.

### PR DESCRIPTION
**Pull request by mlep**
Add of sailplane landing fields for the French Alps, edition 2019.
Taken from http://www.planeur.net/index.php/tlcharger-mainmenuleft-177/file/305-alpes-2019
With some reformatting.

### CODE REVIEW

**Comment by Turbo87** [comment]
@mlep do we have permission to redistribute them?

**Comment by mlep** [comment]
There is no license mentioned on the website. They are made available to the community.

**Comment by Turbo87** [comment]
having no license mentioned legally means that there is a copyright on the data so we can't simply redistribute them...

**Comment by mlep** [comment]
Ah, OK...
I am going to contact the author to find out more about the type of license.

**Pull request merged**
