### PR TITLE
Move USA_PG_REG1-4.cup to waypoints-special/

### PR DESCRIPTION
**Pull request by rawtaz**
Move file that happened to be in the wrong directory.

### CODE REVIEW

**Comment by rawtaz** [comment]
Looks like there's discrepancies in the list of fields, thats why the check fails.

Comparing this file to other .cup files for US, this one has more/different fields listed:

~~~
name,code,country,lat,lon,elev,style,rwdir,rwlen,rwwidth,freq,desc,userdata,pics
~~~

compared to

~~~
name,code,country,lat,lon,elev,style,rwdir,rwlen,freq,desc
~~~

@ventus99 Can you check if you perhaps had some different settings when you generated this file?

**Comment by lordfolken** [comment]
> Looks like there's discrepancies in the list of fields, thats why the check fails.
> 
> Comparing this file to other .cup files for US, this one has more/different fields listed:
> 
> ```
> name,code,country,lat,lon,elev,style,rwdir,rwlen,rwwidth,freq,desc,userdata,pics
> ```
> 
> compared to
> 
> ```
> name,code,country,lat,lon,elev,style,rwdir,rwlen,freq,desc
> ```
> 
> @ventus99 Can you check if you perhaps had some different settings when you generated this file?
looks like naviter via seeyou extended their file format, without telling anyone. 
http://download.naviter.com/docs/CUP-file-format-description.pdf
In there only the name,code,country,lat,lon,elev,style,rwdir,rwlen,freq,desc fields ar e described. 
Since we already have support for rwwidth in the code. we can accept this.

**Comment by lordfolken** [comment]
looks like @ventus99 is already busy on the aerofiles side: https://github.com/Turbo87/aerofiles/pull/217 @rawtaz

**Comment by rawtaz** [comment]
Okay, I figured we should fix the root cause now that we had a clear test case, but you already merged it so :D

**Comment by lordfolken** [comment]
@rawtaz yeah the problem is that it doens't deploy until we have updated aerofiles.

**Pull request merged**
