### PR TITLE
Update Germany airports B-D; E-G update according to the latest DFS list only.

### PR DESCRIPTION
**Pull request by hor63**
Verify and update German airports, glider ports, UL fields and landingfields up and including D...

### CODE REVIEW

**Comment by hor63** [comment]
What a drag.

**Comment by hor63** [comment]
From character E onwards the I restrict the review to the airports which are listed in the current DFS list only to get the list up-to-date for the season as fast as possible.
This list only covers 1/2 at best. The remaining airports are partially updated nevertheless, but a lot others are not.  

The complete review will be left for the next round.

**Comment by fb** [comment]
@hor63 do you use a tool like Excel or LibreOffice Calc for the task?
I just gave it a try. I converted the PDF by DFS to CSV (using [tabula](/tabulapdf/tabula)) and merged it with Germany.cup semi-automatically using LibreOffice.

That's how far I got until now if it's any help: https://gist.github.com/fb/7aa53d4b741c393199662a6985099af6

I think getting the frequencies into Germany.cup would be possible with some more sorting and row shifting (and careful cross-checking afterwards).

**Comment by hor63** [comment]
Manual.
More than half of the sites are not even in the DFS list. That’s looking up OpenAIP OpenFlightmap, look to the coordinates in Google maps (also checking the accuracy of the position, in so Ei stances there are now photovoltaic panels, Ups!) and see what is there and hunt down the web site.
Copy paste the info from the DFS list is so small in comparison, it is not worth the effort to semi-automate it. The naming are also too inconsistent.
Kai

Sent from my iPad

On Mar 21, 2019, at 19:19, Fabian Bartschke <notifications@github.com<mailto:notifications@github.com>> wrote:


@hor63<https://github.com/hor63> do you use a tool like Excel or LibreOffice Calc for the task?
I just gave it a try. I converted the PDF by DFS to CSV (using tabula</tabulapdf/tabula>) and merged it with Germany.cup semi-automatically using LibreOffice.

That's how far I got until now if it's any help: https://gist.github.com/fb/7aa53d4b741c393199662a6985099af6

I think getting the frequencies into Germany.cup would be possible with some more sorting and row shifting (and careful cross-checking afterwards).

**Pull request merged**
