### PR TITLE
Imported xcsoar-data-maps/data/maps.config.js and converted to separate files.

### PR DESCRIPTION
**Pull request by csindle**
These files are generated from `map/`:

1. `maps.json`
2. `maps.repository`
3. `maps.config.js`

---

* `maps.config.js` -> `map/*.json`: Run: `maps_config_js_to_json_files.py` (just for this import)
* `map/*.json` -> `maps.config.js`: Run `generate_map.py` (for use by existing programs and websites)

### CODE REVIEW

**Comment by lordfolken** [comment]
So the important thing is to have one definition which generates:
 * the maps
 * the js file for the download link
 * the repository entries (prefeerably with the coordinates in a new tag)

**Comment by csindle** [comment]
> ...  one definition...

Yes. This is only a draft PR to test our appetites for sorting out XCSoars data content. It might  eventually *replace* `xcsoar-data-maps/data/maps.config.js` and indeed that entire git repository.

Perhaps the first step is just to move `maps.config.js` here. 

And then later, convert it to some more intrinsic format that is easy to maintain, develop, and use. I.e. one map, one file, one separate history.

This is part of https://github.com/XCSoar/xcsoar-data-content/issues/180

**Comment by lordfolken** [comment]
Yes i'm very much for merging all in xcsoar-data-maps. Beware however, this workflow needs to run if a change is detected to the maps declaration files: https://github.com/XCSoar/xcsoar-data-maps/blob/master/.github/workflows/maps-build.yml

**Comment by csindle** [comment]
T.b.h. I am not sure how all these pieces fit together, but taking a step back, [`generate-maps`](https://github.com/XCSoar/mapgen/blob/master/bin/generate-maps#L43) can easily get these proposed `map/*.json` files from this public repository and then generate the maps and `rsync` them across to http://download.xcsoar.org/maps/ .

One option would be for mapgen to run once a day regardless, though of course it would be better to send a signal to it.  We must however not confuse who owns the data/content (this repo) with how artefacts are generated (and we may have to jump through some hoops to minimally use GH Actions).

**Comment by lordfolken** [comment]
The GH action can be triggered only by a change in for example one directory. That way it doesn't run if not needed.

**Comment by csindle** [comment]
Is it that  `mapgen` needs to be simplified firsd?

1. Theoretically, is it possible for one bash script (not GH Action) to take a vanilla Debian/Ubuntu server, install dependencies (including this public repo with `map/*.json`), and then generate the maps? 
2. And then deploy iff authorised?

**Pull request closed without merging**
