### PR TITLE
Add ability to check the URIs of a local repository file.

### PR DESCRIPTION
**Pull request by csindle**
Add ability to check the URIs of a local repository file, instead of just https://download.xcsoar.org/repository.

This means this script could be run as part of a PR check (once this repo takes over generating that the repository file, and the URIs are live, etc.).

### CODE REVIEW

**Review by lordfolken — APPROVED** [review]

**Review by lordfolken — CHANGES_REQUESTED** [review]
Sorry one change please: can you please make it not output anything if no -v or similar is specified? I prefeer the UNIX way:
 * no action if no arguments: display help
 * if successful with arguments no output other than exit code 0
 * if -v or so requested full output
 * failure: exit with error text and exit code

**Comment by csindle** [comment]
> failure: exit with error text and exit code

OK, it will print out only the failures (and then of course a non-zero exit code of 1).

(I don't want to get embroiled in logging levels and argparse boilerplate at this fast moving re-organisation stage of the game. )

**Comment by csindle** [comment]
Please also *permanently* disable these two Codacy complaints. 
(I would provide a link, but they seem ephemeral.)

**Comment by lordfolken** [comment]
We have implemented this check.

**Pull request closed without merging**
