### PR TITLE
added VFR Controlpoints to Austria.cup

### PR DESCRIPTION
**Pull request by Surkes**
added VFR Controlpoints to Austria.cup without any changes from source.
Source-File: https://www.austrocontrol.at/jart/prj3/ac/data/dokumente/austria_acg_waypoints_2019-03-28_2019-02-22_1302179.cup

Source-Homepage: https://www.austrocontrol.at/piloten/vor_dem_flug/aim_produkte/luftraumstruktur

### CODE REVIEW

**Comment by Surkes** [comment]
I added the ICAO code to all control Points to set a consistent syntax over all control points.
I sorted the data so the information in github is -all points +all points...

Should I pull the old Austria.cup and add the ICAO code without sorting?

**Comment by hor63** [comment]
Philipp, is there a reason that you approved the latest 2 pull requests, but did not merge them?

**Comment by lordfolken** [comment]
There are a few conflicts here.. 
* Austrocontrol already publishes these in openair format.
** We are duplicating data already available elsewhere
** How do we integrate future changes from Austrocontrol?
* We made some changes which need to go back to the source
* Is merging official VFR waypoints with unofficial turnpoints a good idea?
* There are limits in xcsoar, since you can only specify two waypoint files.

**Comment by Surkes** [comment]
My understanding of the Austria.cup in the download repo is, that everything of Austria is in there.

I understand your problem with duplicating waypoints but everyone of us has to merge different sources by our own and shares it with our club mates. 
We could save a lot of time if we merge the files here.

One idea from me is, to separate the sources in the file.
Like:
### XCSoar
* Waypoints XCSoar
### Autrocontrol - dateofupstream
* Waypoints Austrocontrol
### Openflightmaps - dateofupstream
* Waypoints Openflightmaps

With this way we could easier check and change upstream changes but have merged all files for Austria.

**Comment by lordfolken** [comment]
I like the approach, that everything is in austria.cup.
We could generate austria.cup dynamically. This repo already has the xcsoar_waypoints.cup file that is generated by the travis CI, from all the files contained here.

So we could periodically fetch all the data from austrocontrol and integrate them into austria.cup.

**Comment by Surkes** [comment]
But if you fetch all the data from austrocontrol you have waypoints with the same names and some waypoints are duplicated like the airfields.

**Pull request merged**
