### PR TITLE
Replace July 2020 airspace with April 2022 airspace.

### PR DESCRIPTION
**Pull request by roeles**
# Pull Request

## The purpose of this change
Bring The Netherlands airspace up to date.

Replace the airspace previously listed (last update: July 2020) with the latest update (April 2022).

## The source of the data (for e.g. new frequencies)
Retreived with permission to copy (as in previous years) from Glider Pilot Shop:
https://www.gliderpilotshop.com/airspace-netherlands-2204.html

Permission (in Dutch) by email:
```
Hallo Roel...plan is die op 22 april te publiceren (AIRAC datum) en ja, je mag die weer gebruiken voor XCSoar.

Op 19 apr. 2022, om 08:35 heeft Roel Baardman het volgende geschreven:

Hey Maurits,

Heb je al een nieuwe versie van het luchtruim in OpenAir online staan? Ik vind hem nog niet op GPS.
Vind je het goed dat ik weer een kopie trek voor gebruik in XCSoar?

groet,

Roel
```

### CODE REVIEW

**Comment by roeles** [comment]
I am not 100% certain that I did everything needed to replace the airspace. I could not find any file containing the name of the old airspace, so I assumed that it was somehow automatically indexed/scraped.

**Comment by lordfolken** [comment]
So this will upload the file and it will show up like eh2007.txt in the file manager, and generally work. 

What would be possible is to add a Netherlands_Airspace.json file in https://github.com/XCSoar/xcsoar-data-content/tree/master/data/remote/airspace/country/ referencing the eh2007 on download.xcsoar.org/content/airspace file. That way you would have an easly identifiable file, and next year you could just upload the new version in the same location, and it would display as an update to the enduser.

**Review by lordfolken — CHANGES_REQUESTED** [review]
Decide on whether go or no/no-go. You can then approve this comment, and it should automerge.

**Comment by roeles** [comment]
Please note that the commit also changes the filename. The file EH2007.txt would be removed and a new file called EH2204.txt would be added. 
I will create an appropriate `Netherlands_Airspace.json` file.

**Review by lordfolken — APPROVED** [review]

**Pull request merged**
